---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: external-dns
    chart: external-dns-0.6.1
    heritage: Tiller
    release: external-dns
  name: external-dns

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: external-dns
    chart: external-dns-0.6.1
    heritage: Tiller
    release: external-dns
  name: external-dns
rules:
- apiGroups:
  - ""
  - extensions
  resources:
  - ingresses
  - services
  - pods
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: external-dns
    chart: external-dns-0.6.1
    heritage: Tiller
    release: external-dns
  name: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: external-dns

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: external-dns
    chart: external-dns-0.6.1
    heritage: Tiller
    release: external-dns
  name: external-dns
spec:
  ports:
  - port: 7979
    protocol: TCP
    targetPort: 7979
  selector:
    app: external-dns
    release: external-dns
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: external-dns
    chart: external-dns-0.6.1
    heritage: Tiller
    release: external-dns
  name: external-dns
spec:
  template:
    metadata:
      labels:
        app: external-dns
        heritage: Tiller
        release: external-dns
    spec:
      containers:
      - args:
        - --log-level=debug
        - --domain-filter=example.com
        - --domain-filter=example.io
        - --domain-filter=example.work
        - --policy=sync
        - --provider=cloudflare
        - --registry=txt
        - --txt-owner-id=digitalocean
        - --txt-prefix=do
        - --source=service
        - --source=ingress
        env:
        - name: CF_API_EMAIL
          valueFrom:
            secretKeyRef:
              key: CF_API_EMAIL
              name: external-dns
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              key: CF_API_KEY
              name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.5.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 7979
        name: external-dns
        ports:
        - containerPort: 7979
      serviceAccountName: external-dns

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: external-dns
  name: external-dns

